topsky/GRpluginSettings.txt

Adjusts LVP LVP RIMCAS to 140m, testing needed.

LVP adjustment

---

README.md

actually writes a readme

---

topsky/GRpluginSettings.txt

Activates ground radar pro mode and sets primary radar close to what it is irl

Ground Radar Professional Edition(tm)

---

LPPC_CTR_TS.prf

Just so all the settings paths are there

TopSky profile

---

LPPC/Settings/Symbology.txt

turns out some colors were out of date

updates colors

---

LPPC/Settings/DepartureList_TopSky.txt

Removes stand menu action from departure menu, stand menu is for arrivals only, not departures

remove stand menu

---

topsky/TopSkySettings.txt

Notam provider changed names, works again now yay

Update NOTAM provider

---

LPPC/Settings/General_TopSky.txt

Zoom under mouse

---

LPPC/Plugins/topsky/TopSkySettingsLocal.txt

GUESS WHO FORGOT PORTO AND FARO EXISTS YEAH

5mn STCA in TMAs

---

LPPC/ASR/LPCS_TWR.asr

Fixes cascais being legally blind

---

README.md

Update readme pictures

---

LPPC/Plugins/topsky/GRpluginSettingsLocal.txt

You can change settings in this file so things better fit in your resolution

Ground radar example local settings

---

LPPC/ASR/LPPC_CTR_TS.asr

Fixes southern spain being swallowed by the atlantic ocean

---

LPPC/Settings/General_TopSky.txt

not really ts related but still necessary

Add lvp option to atis

---

LPPC/Plugins/topsky/GRpluginSettings.txt

Display stand in approach window labels

---

LPPC/Settings/Tags_TopSky.txt

Fixes missing CPDLC warning functions

---

LPPC/Plugins/topsky/TopSkyCPDLC.txt
LPPC/Plugins/topsky/TopSkySettings.txt

Update DCL format to known spec

FSM Header

---

LPPC/Plugins/topsky/TopSkyCPDLC.txt
LPPC/Plugins/topsky/TopSkySettings.txt

Fixes DCL times to be 3 minutes
Adjusts spacing for maximum realism

Spacing and timing

---

LPPC/Plugins/topsky/TopSkySettings.txt

remove double pdc header https://cdn.discordapp.com/attachments/775019508737638402/919629298447560774/unknown.png

update dcl format

---

LPPC/Plugins/topsky/GRpluginSettings.txt

Enable new lists in GR

---

LPPC/Settings/Plugins.txt

Fixes CFL collumn

---

LPPC/Settings/Tags_TopSky.txt

Adds toggle frequency action on label

---

LPPC/Settings/Symbology_TopSky.txt

Datablock - Detailed background
Sector - Inactive sector background
fixes #333

Grey tweaks

---

LPPC/Settings/Tags_TopSky.txt

update tag dest action

---

LPPC/Plugins/topsky/TopSkySettings.txt

APW settings

---

LPPC/Settings/Symbology_TopSky.txt

METAR colors

---

LPPC/Plugins/topsky/TopSkySettings.txt
LPPC/Settings/Tags_TopSky.txt

Fixes #325 
fixes #353 
Fixes #328 
Fixes #323 
Fixes #322 FOR GOOD
Fields 15 and 18 display up to 6 rows

Label fixes

---

LPPC/Settings/DepartureList_TopSky.txt

Fix missing TSAT actions

---

LPPC/Settings/Plugins.txt

List fixes

---

LPPC/Plugins/topsky/TopSkySettings.txt
LPPC/Settings/Tags_TopSky.txt

Fixes DAP label settings

---

LPPC/Settings/Tags_TopSky.txt

Hides a bunch of items in unselected tag

Unselected tag fix

---

LPPC/Settings/Tags_TopSky.txt

removes TOG in unselected labels

Unselected TOG

---

LPPC/Settings/Tags_TopSky.txt

Generally, left click highlights, right click toggles show
Fixes #388

Adds missing unselected label toggles

---

LPPC/Settings/Plugins.txt

Adds more rows to Sector list

---

LPPC/Settings/Tags_TopSky.txt

Fixes #399 
COPX Waypoint Menu | Toggle FLeg
FCOPX            nothing | Toggle FCOPX

FCOPX consistency

---

LPPC/Plugins/topsky/TopSkySettings.txt
LPPC/Settings/DepartureList_TopSky.txt
LPPC/Settings/Screen_TopSky.txt

DEP list should save position now

Minor window position adjustments

---

LPPC/Settings/Tags_TopSky.txt

C/S or TSSR or FLTID
Fixes #403

Anchors to line 1 first element

---

LPPC_CTR_TS.prf

sorts things
loads plugins
sets position of vccs
fixes #414
fixes  #416 
fixes #423 
fixes #424

Adds missing plugins

---

LPPC/Settings/Screen_TopSky.txt
LPPC_CTR_TS.prf

atis freq - useful to see if atis is ok or kaput by checking for 199.998 vccs display - to endeavour vccs use

enables atis freq and vccs display

---

LPPC/Plugins/topsky/TopSkySettings.txt

Update RAM Divergence threshold

---

LPPC/Settings/Tags_TopSky.txt

Fixes jumping tag issues

---

README.md

update readme for toplis implementation

---

manifest.json

Test json manifest

---

README.md

Better version control on readme

---

LPPC/Plugins/ACDM/CAD/CAD_Portugal.txt

In preparation of [CDM CAD](https://github.com/rpuig2001/CDM#future-cad---capacity-availability-document)

CAD Portugal

---

LPPC/Settings/Tags_TopSky.txt

Track label fixes

---

LPPC/Plugins/topsky/TopSkySettings.txt

Fixes APW for VFR

---

LPPC/Settings/Tags_TopSky.txt

Restores flight leg by RMB in FCOPX

---

LPPC/Settings/VCCS.txt

finally a good server
updated in gng

update vccs server

---

LPPC/Settings/General_TopSky.txt

Update ATIS URL

---

LPPC/Plugins/topsky/Documentation/Latex/TOPLIS/TOPLIS Manual.tex
LPPC/Plugins/topsky/Documentation/TOPLIS Manual.pdf
LPPC/Settings/Tags_TopSky.txt

Adds FLeg display to RMB on MTCD Indicator

---

LPPC/Plugins/topsky/TopSkySettings.txt

Fixes Notams not showing i guess

Updates METAR and NOTAM API URL

---

LPPC/Plugins/GroundRadar/GRpluginSettings.txt

probably needs to be reverted on new ground radar version

Adds Croatia to Schengen area

---

LPPC/Settings/Plugins.txt

Fixes TML2 ETO

---

LPPC/Settings/Symbology_TopSky.txt

blue departures, orange arrivals
fixes #578

Fixes swapped colors on non ground radar ground displays

---

LPPC/Plugins/topsky/TopSkySettings.txt

Updates max QDM number to 50 according to B3.7

Update MAX QDM as per B3.7

---

LPPC/Plugins/topsky/TopSkySettings.txt

Removes Message Out window

---

LPPC/Plugins/topsky/TopSkySettings.txt

Move Message In Window to bottom of screen

---

LPPC/Plugins/topsky/TopSkySettings.txt

TML defaults apply to entire airport, instead of specific APP positions

More scalable TML default

---

LPPC/Plugins/GroundRadar/GRpluginSettings.txt

Fixes GRPlugin comments syntax

---

LPPC/Plugins/topsky/TopSkySettings.txt

Temporary fix while areas are not constructed properly
Fixes #635

Temporary fix for vertical separation of RVSM areas

---

.github/workflows/main.yml

Fixes latex job

---

LPPC/Settings/Plugins.txt

Fixes SI collumns being too smol

---

LPPC/Plugins/topsky/TopSkySettings.txt

Update TAF URL

---

LPPC/Plugins/ACDM/CDMconfig.xml

Unleashes hell

---

index.md

Updated instalation guide

---

LPPC/Plugins/topsky/TopSkySettings.txt

Update traffic managment list 1

---

LPPC/Plugins/ACDM/CAD/CAD_Portugal.txt

Temporary Capacity reduction CAD LPPT

---

LPPC/Plugins/ACDM/CDMconfig.xml

LPPT departure capacity reduction

---

LPPC/Plugins/topsky/TopSkySettings.txt

Missing traffic management list setting for LPPT_APP

---

LPPC/ASR/LPCS_TWR.asr

Add LPVZ groundlayout

---

README.md

https://forum.vatsim-scandinavia.org/d/65-topsky-plugin-25-beta-13

TopSky 2.5.13

---

LPPC ACS.prf
LPPC APS.prf

Fixes erroneous ATIS frequencies

Wrong ATIS frequencies

---

LPPC ACS.prf
LPPC APS.prf
LPPC/Settings/General_TopSky.txt

https://vatatis.vatsim.pt/api/docs

New ATIS source

---

LPPC/Settings/General_TopSky.txt

Update mode S capable codes

---

LPPC/Plugins/ACDM/CAD/CAD_Portugal.txt

This reverts commit 48b447922d4872bd16b7e6f92efd44529c8a4c10.

Revert "Temporary Capacity reduction CAD LPPT (#735)"

---

LPPC ACS.prf
LPPC APS.prf

atis lvo parameters

---

LPPC/Plugins/topsky/TopSkySettings.txt

Enables PotRisk display
Sets width to always be 1px

Flightleg update

---

LPPC/Plugins/topsky/TopSkySettings.txt

Update PLC reminder time value

---

LPPC/Plugins/topsky/TopSkySettings.txt

Flight leg does increase in thickness. TS plugin has the wrong conditions to increase

Reverts FlightLeg pixel changes

---

LPPC/ASR/LPCS_TWR.asr

LPCS new taxiway layout

---

LPPC/Plugins/topsky/TopSkySettings.txt

DRC DAPs on unselected labels in APP and TWR

---

LPPC/Settings/General_TopSky.txt

Enables mode-s correlation

---

LPPC/Plugins/GroundRadar/GRpluginSettings.txt

Moved RVR and Alerts list to create a themed based clusters of information

Add QNH and METAR windows to Ground Radar

---

LPPC/Plugins/topsky/TopSkySettings.txt

Add half assed Informed state rules

Informed state

---

LPPC/Plugins/GroundRadar/GRpluginSettings.txt

Force GR to use sector file mode A and S

---

LPPC/Plugins/GroundRadar/GRpluginSettings.txt

Always show Stand List

---

LPPC/Plugins/topsky/TopSkySettings.txt

Disable P-RNAV airports

---

LPPC/Plugins/topsky/TopSkyMaps.txt

Add 🇵🇹🇵🇹🇵🇹Selvagens🇵🇹🇵🇹🇵🇹🇵🇹🇵🇹 to shore map

---

LPPC/Plugins/topsky/TopSkyMaps.txt

Add LPAZ TMA, Sao Miguel and Santa Maria islands

---

LPPC/ASR/LPFR_GND_TSGR.asr
LPPC/Plugins/GroundRadar/GRpluginSettings.txt

Implementation similar to LPPT and LPPR, without safety nets and history trails

Implement Groundradar at LPFR

---

LPPC/Plugins/GroundRadar/GRpluginSettings.txt

New Ground Radar window layouts
